import 'package:blood_donation_app/core/resources/colors/color_manger.dart';
import 'package:blood_donation_app/core/widgets/custom_elevated_button.dart';
import 'package:blood_donation_app/core/widgets/custom_text.dart';
import 'package:blood_donation_app/presentation/role/admin/tabs/dashboard/widgets/donor_tile.dart';
import 'package:blood_donation_app/presentation/role/hospital/tabs/home/section/request_header.dart';
import 'package:flutter/material.dart';

import '../../../../../../core/resources/fonts/font_manger.dart';
import '../../../../../../core/resources/models/donor.dart';
import '../../../../../../l10n/app_localizations.dart';

class ShowAllDonorsDialog extends StatelessWidget {
  const ShowAllDonorsDialog({super.key});

  @override
  Widget build(BuildContext context) {
    final appLocalization = AppLocalizations.of(context)!;
    final List<DonorModel> donors = [
      DonorModel(
        id: '1',
        name: "Ahmed Mohamed",
        email: "ahmed@gmail.com",
        phoneNumber: "01012345678",
        bloodType: "O+",
        totalDonations: 12,
        points: 240,
        isEligibleToDonate: true,
        location: "Cairo",
        isActive: true,
        isVerified: true,
        gender: "Male",
        age: 25,
        weight: 75,
        healthStatus: "Good",
        isBanned: false,
        isOnline: true,
        createdAt: DateTime(2023, 5, 10),
        donorRank: 1,
      ),
      DonorModel(
        id: '2',
        name: "Sara Ali",
        email: "sara@gmail.com",
        phoneNumber: "01198765432",
        bloodType: "A-",
        totalDonations: 5,
        points: 100,
        isEligibleToDonate: true,
        location: "Alexandria",
        isActive: true,
        isVerified: true,
        gender: "Female",
        age: 22,
        weight: 60,
        healthStatus: "Excellent",
        isBanned: false,
        isOnline: false,
        createdAt: DateTime(2024, 1, 15),
        donorRank: 2,
      ),
      DonorModel(
        id: '3',
        name: "Omar Hassan",
        email: "omar@gmail.com",
        phoneNumber: "01222222222",
        bloodType: "B+",
        totalDonations: 20,
        points: 400,
        isEligibleToDonate: false,
        location: "Giza",
        isActive: true,
        isVerified: true,
        gender: "Male",
        age: 30,
        weight: 85,
        healthStatus: "Average",
        isBanned: false,
        isOnline: true,
        createdAt: DateTime(2022, 8, 3),
        donorRank: 3,
      ),
      DonorModel(
        id: '4',
        name: "Mona Adel",
        email: "mona@gmail.com",
        phoneNumber: "01055555555",
        bloodType: "AB+",
        totalDonations: 2,
        points: 40,
        isEligibleToDonate: true,
        location: "Mansoura",
        isActive: true,
        isVerified: false,
        gender: "Female",
        age: 28,
        weight: 65,
        healthStatus: "Good",
        isBanned: false,
        isOnline: false,
        createdAt: DateTime(2024, 6, 20),
        donorRank: 4,
      ),
      DonorModel(
        id: '5',
        name: "Youssef Tarek",
        email: "youssef@gmail.com",
        phoneNumber: "01544444444",
        bloodType: "O-",
        totalDonations: 15,
        points: 300,
        isEligibleToDonate: false,
        location: "Tanta",
        isActive: false,
        isVerified: true,
        gender: "Male",
        age: 27,
        weight: 78,
        healthStatus: "Good",
        isBanned: true,
        isOnline: false,
        createdAt: DateTime(2021, 11, 11),
        donorRank: 5,
      ),
      DonorModel(
        id: '6',
        name: "Hassan Mostafa",
        email: "hassan@gmail.com",
        phoneNumber: "01077777777",
        bloodType: "A+",
        totalDonations: 8,
        points: 160,
        isEligibleToDonate: true,
        location: "Cairo",
        isActive: true,
        isVerified: true,
        gender: "Male",
        age: 29,
        weight: 80,
        healthStatus: "Good",
        isBanned: false,
        isOnline: true,
        createdAt: DateTime(2023, 9, 12),
        donorRank: 2,
      ),
      DonorModel(
        id: '7',
        name: "Nour El Din",
        email: "nour@gmail.com",
        phoneNumber: "01122223333",
        bloodType: "B-",
        totalDonations: 3,
        points: 60,
        isEligibleToDonate: true,
        location: "Alexandria",
        isActive: true,
        isVerified: false,
        gender: "Male",
        age: 21,
        weight: 68,
        healthStatus: "Excellent",
        isBanned: false,
        isOnline: false,
        createdAt: DateTime(2024, 3, 5),
        donorRank: 4,
      ),
      DonorModel(
        id: '8',
        name: "Fatma Khaled",
        email: "fatma@gmail.com",
        phoneNumber: "01599999999",
        bloodType: "O+",
        totalDonations: 10,
        points: 200,
        isEligibleToDonate: true,
        location: "Giza",
        isActive: true,
        isVerified: true,
        gender: "Female",
        age: 26,
        weight: 62,
        healthStatus: "Good",
        isBanned: false,
        isOnline: true,
        createdAt: DateTime(2022, 12, 1),
        donorRank: 2,
      ),
      DonorModel(
        id: '9',
        name: "Karim Adel",
        email: "karim@gmail.com",
        phoneNumber: "01288888888",
        bloodType: "AB-",
        totalDonations: 1,
        points: 20,
        isEligibleToDonate: false,
        location: "Mansoura",
        isActive: true,
        isVerified: false,
        gender: "Male",
        age: 24,
        weight: 70,
        healthStatus: "Weak",
        isBanned: false,
        isOnline: false,
        createdAt: DateTime(2024, 7, 10),
        donorRank: 5,
      ),
      DonorModel(
        id: '10',
        name: "Salma Ibrahim",
        email: "salma@gmail.com",
        phoneNumber: "01066666666",
        bloodType: "A+",
        totalDonations: 14,
        points: 280,
        isEligibleToDonate: true,
        location: "Tanta",
        isActive: true,
        isVerified: true,
        gender: "Female",
        age: 31,
        weight: 67,
        healthStatus: "Excellent",
        isBanned: false,
        isOnline: true,
        createdAt: DateTime(2021, 6, 18),
        donorRank: 1,
      ),
    ];
    return Dialog(
      insetPadding: const EdgeInsets.symmetric(horizontal: 20),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      backgroundColor: ColorManger.pureWhite,
      child: SafeArea(
        child: SizedBox(
          width: MediaQuery.of(context).size.width * 0.95,
          child: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  RequestHeader(
                    title: appLocalization.allTopDonors,
                    subtitle:
                        appLocalization.allTopDonorsSubtitle,
                  ),
                  SizedBox(height: 16),
                  ListView.builder(
                    physics: NeverScrollableScrollPhysics(),
                    shrinkWrap: true,
                    itemCount: donors.length,
                    itemBuilder: (context, index) {
                      final donor = donors[index];
                      return Padding(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 16.0,
                          vertical: 8,
                        ),
                        child: DonorTile(
                          donor: donor,
                          showLastDonation: true,
                          showActivityStatus: true,
                        ),
                      );
                    },
                  ),
                  SizedBox(height: 32),
                  CustomElevatedButton(
                    padding: EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                    backgroundColor: ColorManger.brightPurple,
                    onPressed: () {
                      Navigator.pop(context);
                    },
                    foregroundColor: ColorManger.pureWhite,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: CustomText(
                      text: appLocalization.close,
                      textStyle: TextStyle(
                        fontSize: FontSize.s14,
                        color: ColorManger.pureWhite,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
