// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMVF6FL5pTzmiQW19HXIB2UsxYKlLtMbc',
    appId: '1:560687465611:web:3288b5fe2680db84e3c08e',
    messagingSenderId: '560687465611',
    projectId: 'lifelink-3bb82',
    authDomain: 'lifelink-3bb82.firebaseapp.com',
    storageBucket: 'lifelink-3bb82.firebasestorage.app',
    measurementId: 'G-31CVQTZJSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2p7KWTBl-QkgY_roo4T7ji8pT8NNP1MQ',
    appId: '1:560687465611:android:9ca8584666d662f9e3c08e',
    messagingSenderId: '560687465611',
    projectId: 'lifelink-3bb82',
    storageBucket: 'lifelink-3bb82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVDD-a-6v9vy3wdcHY2T2XBSs-Y3uPcs',
    appId: '1:560687465611:ios:df61d07c82f42d3ee3c08e',
    messagingSenderId: '560687465611',
    projectId: 'lifelink-3bb82',
    storageBucket: 'lifelink-3bb82.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLVDD-a-6v9vy3wdcHY2T2XBSs-Y3uPcs',
    appId: '1:560687465611:ios:df61d07c82f42d3ee3c08e',
    messagingSenderId: '560687465611',
    projectId: 'lifelink-3bb82',
    storageBucket: 'lifelink-3bb82.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMVF6FL5pTzmiQW19HXIB2UsxYKlLtMbc',
    appId: '1:560687465611:web:917550dc0cc7e1b2e3c08e',
    messagingSenderId: '560687465611',
    projectId: 'lifelink-3bb82',
    authDomain: 'lifelink-3bb82.firebaseapp.com',
    storageBucket: 'lifelink-3bb82.firebasestorage.app',
    measurementId: 'G-CM3CJCBY6V',
  );
}
